# Generated by Django 5.0.14 on 2026-06-22 02:43

import apps.ledger.constants
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PROPERTY', 'Property'), ('VEHICLE', 'Vehicle'), ('SUPERANNUATION', 'Superannuation'), ('INVESTMENT', 'Investment'), ('OTHER', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('currency', models.CharField(max_length=3, validators=[apps.ledger.constants.validate_currency_code])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_classes', to='entities.entity')),
            ],
            options={
                'ordering': ['entity', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetValuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valuation_date', models.DateField()),
                ('current_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(max_length=3, validators=[apps.ledger.constants.validate_currency_code])),
                ('source', models.CharField(blank=True, help_text='e.g. REA estimate, super fund statement, own estimate', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuations', to='assets.assetclass')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valuation_date'],
                'get_latest_by': 'valuation_date',
            },
        ),
        migrations.AddIndex(
            model_name='assetclass',
            index=models.Index(fields=['entity', 'category'], name='assets_asse_entity__065b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='assetvaluation',
            index=models.Index(fields=['asset', 'valuation_date'], name='assets_asse_asset_i_1589d9_idx'),
        ),
    ]
