# Generated by Django 5.0.14 on 2026-06-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetclass',
            options={'ordering': ['entity', 'category', 'name'], 'verbose_name_plural': 'asset classes'},
        ),
    ]
