# Generated by Django 5.0.14 on 2026-06-20 08:18

import apps.ledger.constants
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('from_currency', models.CharField(max_length=3, validators=[apps.ledger.constants.validate_currency_code])),
                ('to_currency', models.CharField(max_length=3, validators=[apps.ledger.constants.validate_currency_code])),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('source', models.CharField(default='frankfurter.dev', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'from_currency', 'to_currency'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', '-date'], name='currencies__from_cu_31ad30_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('date', 'from_currency', 'to_currency', 'source'), name='unique_exchange_rate_per_date_pair_source'),
        ),
    ]
