# Generated by Django 5.0.14 on 2026-06-23 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Google Sheets net worth sync'", max_length=255)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_prefix', models.CharField(editable=False, help_text='First 8 characters, for identifying a token in a list', max_length=8)),
                ('scope', models.CharField(choices=[('READ_ONLY', 'Read only')], default='READ_ONLY', max_length=16)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
