# Generated by Django 5.0.14 on 2026-06-23 10:20

import apps.ledger.constants
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('APPLIANCES', 'Appliances'), ('FURNITURE', 'Furniture'), ('TOOLS', 'Tools'), ('CLOTHING', 'Clothing'), ('JEWELLERY', 'Jewellery'), ('COLLECTIBLES', 'Collectibles'), ('OTHER', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, help_text='e.g. Mount Gambier house -- living room', max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('estimated_replacement_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('currency', models.CharField(max_length=3, validators=[apps.ledger.constants.validate_currency_code])),
                ('insured', models.BooleanField(default=False)),
                ('insurer', models.CharField(blank=True, max_length=255)),
                ('policy_number', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inventory/')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='entities.entity')),
            ],
            options={
                'ordering': ['entity', 'category', 'name'],
                'indexes': [models.Index(fields=['entity', 'category'], name='inventory_i_entity__b2e606_idx'), models.Index(fields=['entity', 'insured'], name='inventory_i_entity__e1628d_idx')],
            },
        ),
    ]
