# Generated by Django 5.0.14 on 2026-06-23 10:40

import apps.ledger.constants
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_initial'),
        ('ledger', '0006_alter_account_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('payment_date', models.DateField()),
                ('currency', models.CharField(max_length=3, validators=[apps.ledger.constants.validate_currency_code])),
                ('gross_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('deduction_tax', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('deduction_fuel_card', models.DecimalField(decimal_places=4, default=0, help_text='Personal expense recovery -- fuel card benefit repayment', max_digits=19)),
                ('deduction_social_club', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('deduction_cfmeu', models.DecimalField(decimal_places=4, default=0, help_text='CFMEU union dues', max_digits=19)),
                ('deduction_pretax_lease', models.DecimalField(decimal_places=4, default=0, help_text='Pre-tax salary sacrifice -- vehicle or equipment lease', max_digits=19)),
                ('net_pay', models.DecimalField(decimal_places=4, max_digits=19)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('cfmeu_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='entities.entity')),
                ('fuel_card_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('income_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslip', to='ledger.journalentry')),
                ('pretax_lease_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('social_club_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('tax_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['entity', 'payment_date'], name='payroll_pay_entity__9a56b6_idx')],
            },
        ),
    ]
