# Generated by Django 5.0.14 on 2026-06-20 07:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('native_currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='entities.entity')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.account')),
            ],
            options={
                'ordering': ['entity', 'account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='entities.entity')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('credit_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='ledger.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.journalentry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['entity', 'account_type'], name='ledger_acco_entity__9d452e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entity', 'entry_date'], name='ledger_jour_entity__04f18d_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit_amount', 0), ('debit_amount__gt', 0)), models.Q(('credit_amount__gt', 0), ('debit_amount', 0)), _connector='OR'), name='journal_line_exactly_one_side_nonzero'),
        ),
        # Deferred constraint trigger: the real "debits = credits" guarantee.
        # Fires once at transaction COMMIT (not per-row), so it can sum all
        # JournalLine rows for a journal_entry_id and reject the whole
        # transaction if they don't balance -- regardless of which code path
        # (service layer, shell_plus, admin, a future API bug) wrote the rows.
        # A plain CheckConstraint can't express this since it can't sum
        # across sibling rows.
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION ledger_check_journal_entry_balanced()
            RETURNS TRIGGER AS $$
            DECLARE
                affected_entry_id UUID;
                imbalance NUMERIC;
            BEGIN
                affected_entry_id := COALESCE(NEW.journal_entry_id, OLD.journal_entry_id);
                SELECT COALESCE(SUM(debit_amount) - SUM(credit_amount), 0) INTO imbalance
                FROM ledger_journalline
                WHERE journal_entry_id = affected_entry_id;
                IF imbalance != 0 THEN
                    RAISE EXCEPTION
                        'Journal entry % is not balanced (debits - credits = %)',
                        affected_entry_id, imbalance;
                END IF;
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;

            CREATE CONSTRAINT TRIGGER journal_entry_balanced_trigger
                AFTER INSERT OR UPDATE OR DELETE ON ledger_journalline
                DEFERRABLE INITIALLY DEFERRED
                FOR EACH ROW EXECUTE FUNCTION ledger_check_journal_entry_balanced();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS journal_entry_balanced_trigger ON ledger_journalline;
            DROP FUNCTION IF EXISTS ledger_check_journal_entry_balanced();
            """,
        ),
    ]
