# Generated by Django 5.0.14 on 2026-06-20 08:12

import apps.ledger.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='native_currency',
            field=models.CharField(max_length=3, validators=[apps.ledger.constants.validate_currency_code]),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='currency',
            field=models.CharField(max_length=3, validators=[apps.ledger.constants.validate_currency_code]),
        ),
        # The original trigger summed debit/credit as one flat total across
        # ALL lines in an entry, regardless of currency -- meaning a 100 AUD
        # debit and a 100 CNY credit incorrectly "balanced". Multi-currency
        # entries (e.g. an AUD/CNY transfer via per-currency FX clearing
        # accounts) must balance independently within each currency present.
        # The trigger itself is untouched; only the function body changes.
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION ledger_check_journal_entry_balanced()
            RETURNS TRIGGER AS $$
            DECLARE
                affected_entry_id UUID;
                imbalanced_currency TEXT;
                imbalance NUMERIC;
            BEGIN
                affected_entry_id := COALESCE(NEW.journal_entry_id, OLD.journal_entry_id);

                SELECT currency, SUM(debit_amount) - SUM(credit_amount)
                INTO imbalanced_currency, imbalance
                FROM ledger_journalline
                WHERE journal_entry_id = affected_entry_id
                GROUP BY currency
                HAVING SUM(debit_amount) - SUM(credit_amount) != 0
                LIMIT 1;

                IF imbalanced_currency IS NOT NULL THEN
                    RAISE EXCEPTION
                        'Journal entry % is not balanced in % (debits - credits = %)',
                        affected_entry_id, imbalanced_currency, imbalance;
                END IF;
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            CREATE OR REPLACE FUNCTION ledger_check_journal_entry_balanced()
            RETURNS TRIGGER AS $$
            DECLARE
                affected_entry_id UUID;
                imbalance NUMERIC;
            BEGIN
                affected_entry_id := COALESCE(NEW.journal_entry_id, OLD.journal_entry_id);
                SELECT COALESCE(SUM(debit_amount) - SUM(credit_amount), 0) INTO imbalance
                FROM ledger_journalline
                WHERE journal_entry_id = affected_entry_id;
                IF imbalance != 0 THEN
                    RAISE EXCEPTION
                        'Journal entry % is not balanced (debits - credits = %)',
                        affected_entry_id, imbalance;
                END IF;
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;
            """,
        ),
    ]
