# Generated by Django 5.0.14 on 2026-06-20 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_fix_per_currency_balance_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=4, max_digits=19)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_records', to='ledger.account')),
                ('reconciled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date'],
                'indexes': [models.Index(fields=['account', '-statement_date'], name='ledger_reco_account_3f6ea2_idx')],
            },
        ),
    ]
