# Generated by Django 5.0.14 on 2026-06-20 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('ledger', '0003_journalline_cleared_reconciliationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='budgets.project'),
        ),
    ]
