# Generated by Django 5.0.14 on 2026-06-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_journalentry_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_cash_equivalent',
            field=models.BooleanField(default=False),
        ),
    ]
