# Generated by Django 5.0.14 on 2026-06-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_account_is_cash_equivalent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], help_text="ASSET: bank accounts, cash, property, investments, superannuation. LIABILITY: credit cards, loans, mortgages. EQUITY: owner's capital/drawings. INCOME: salary, wages, business revenue. EXPENSE: everyday spending.", max_length=16),
        ),
    ]
