# Generated by Django 5.0.14 on 2026-06-20 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='members',
            field=models.ManyToManyField(related_name='entities', through='entities.EntityMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='entitymembership',
            index=models.Index(fields=['entity', 'role'], name='entities_en_entity__ec1989_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitymembership',
            constraint=models.UniqueConstraint(fields=('user', 'entity'), name='unique_user_entity_membership'),
        ),
    ]
