# Generated by Django 5.0.14 on 2026-06-20 23:49

import apps.ledger.constants
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_initial'),
        ('ledger', '0003_journalline_cleared_reconciliationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('budget_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(max_length=3, validators=[apps.ledger.constants.validate_currency_code])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='entities.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('target_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_goals', to='entities.entity')),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_goals', to='ledger.account')),
            ],
            options={
                'ordering': ['target_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('CUSTOM', 'Custom')], max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('budgeted_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('include_descendants', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='ledger.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='entities.entity')),
            ],
            options={
                'ordering': ['-period_start', 'account__name'],
                'indexes': [models.Index(fields=['entity', 'account', 'period_start'], name='budgets_bud_entity__e6b6cf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gte', models.F('period_start'))), name='budget_period_end_not_before_start'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['entity', 'status'], name='budgets_pro_entity__c60b10_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['entity', 'target_date'], name='budgets_sav_entity__e74319_idx'),
        ),
    ]
