# Generated by Django 5.0.14 on 2026-06-20 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0003_journalline_cleared_reconciliationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_column', models.CharField(max_length=255)),
                ('date_format', models.CharField(max_length=64)),
                ('description_column', models.CharField(max_length=255)),
                ('memo_column', models.CharField(blank=True, max_length=255)),
                ('amount_convention', models.CharField(choices=[('SIGNED_AMOUNT', 'Single signed amount column'), ('DEBIT_CREDIT', 'Separate debit/credit columns')], max_length=16)),
                ('amount_column', models.CharField(blank=True, max_length=255)),
                ('debit_column', models.CharField(blank=True, max_length=255)),
                ('credit_column', models.CharField(blank=True, max_length=255)),
                ('type_column', models.CharField(blank=True, max_length=255)),
                ('type_debit_value', models.CharField(blank=True, max_length=64)),
                ('balance_column', models.CharField(blank=True, max_length=255)),
                ('has_header_row', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='ledger.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_format', models.CharField(choices=[('CSV', 'CSV'), ('OFX', 'OFX')], max_length=8)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PREVIEW', 'Preview'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='PREVIEW', max_length=16)),
                ('statement_start_date', models.DateField(blank=True, null=True)),
                ('statement_end_date', models.DateField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='ledger.account')),
                ('column_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='imports.columnmapping')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('memo', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('external_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('POSTED', 'Posted'), ('IGNORED', 'Ignored')], default='UNMATCHED', max_length=16)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_transactions', to='ledger.account')),
                ('created_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.journalentry')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='imports.importbatch')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_imports', to='ledger.journalline')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='columnmapping',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='unique_mapping_name_per_account'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['account', '-created_at'], name='imports_imp_account_e2efe9_idx'),
        ),
        migrations.AddIndex(
            model_name='importedtransaction',
            index=models.Index(fields=['account', 'status'], name='imports_imp_account_03bfe0_idx'),
        ),
        migrations.AddIndex(
            model_name='importedtransaction',
            index=models.Index(fields=['account', 'transaction_date'], name='imports_imp_account_32f081_idx'),
        ),
        migrations.AddConstraint(
            model_name='importedtransaction',
            constraint=models.UniqueConstraint(fields=('account', 'external_id'), name='unique_imported_transaction_per_account_external_id'),
        ),
        migrations.AddConstraint(
            model_name='importedtransaction',
            constraint=models.CheckConstraint(check=models.Q(('matched_line__isnull', True), ('created_entry__isnull', True), _connector='OR'), name='imported_transaction_not_both_matched_and_created'),
        ),
    ]
